# ---------------------------------------------------------------------
# Function to add config defines to a list that depends on a namespace variable
# #defines that match the namespace can later be written out to a file
# ---------------------------------------------------------------------
function(EXAMPI_LIBFABRIC_add_config_define_namespace)
  set(options)
  set(one_value_args DEFINE NAMESPACE)
  set(multi_value_args VALUE)
  cmake_parse_arguments(OPTION "${options}" "${one_value_args}"
                        "${multi_value_args}" ${ARGN})

  set(DEF_VAR EXAMPI_LIBFABRIC_CONFIG_DEFINITIONS_${OPTION_NAMESPACE})

  # to avoid extra trailing spaces (no value), use an if check
  if(OPTION_VALUE)
    set_property(GLOBAL APPEND PROPERTY ${DEF_VAR}
                                        "${OPTION_DEFINE} ${OPTION_VALUE}")
  else()
    set_property(GLOBAL APPEND PROPERTY ${DEF_VAR} "${OPTION_DEFINE}")
  endif()
endfunction()

# ---------------------------------------------------------------------
# Function to write out all the config defines for a given namespace into a
# config file
# ---------------------------------------------------------------------
function(EXAMPI_LIBFABRIC_write_config_defines_file)
  set(options)
  set(one_value_args TEMPLATE NAMESPACE FILENAME)
  set(multi_value_args)
  cmake_parse_arguments(OPTION "${options}" "${one_value_args}"
                        "${multi_value_args}" ${ARGN})

  get_property(DEFINITIONS_VAR GLOBAL
               PROPERTY EXAMPI_LIBFABRIC_CONFIG_DEFINITIONS_${OPTION_NAMESPACE})

  if(DEFINED DEFINITIONS_VAR)
    list(SORT DEFINITIONS_VAR)
    list(REMOVE_DUPLICATES DEFINITIONS_VAR)
  endif()

  set(project_config_defines "\n")
  foreach(def ${DEFINITIONS_VAR})
    set(project_config_defines "${project_config_defines}#define ${def}\n")
  endforeach()

  # if the user has not specified a template, generate a proper header file
  if(NOT OPTION_TEMPLATE)
    string(TOUPPER ${OPTION_NAMESPACE} NAMESPACE_UPPER)
    set(PREAMBLE
        "\n"
        "// Do not edit this file! It has been generated by the cmake configuration step.\n"
        "\n"
        "#ifndef EXAMPI_LIBFABRIC_CONFIG_${NAMESPACE_UPPER}_HPP\n"
        "#define EXAMPI_LIBFABRIC_CONFIG_${NAMESPACE_UPPER}_HPP\n")
    set(TEMP_FILENAME
        "${PROJECT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/${NAMESPACE_UPPER}")
    file(WRITE ${TEMP_FILENAME} ${PREAMBLE} ${project_config_defines}
                                "#endif\n")
    configure_file("${TEMP_FILENAME}" "${OPTION_FILENAME}" COPYONLY)
    file(REMOVE "${TEMP_FILENAME}")
  else()
    message("configure_file("${OPTION_TEMPLATE}" "${OPTION_FILENAME}" @ONLY)")
    configure_file("${OPTION_TEMPLATE}" "${OPTION_FILENAME}" @ONLY)
  endif()
endfunction()

include(CMakeParseArguments)

# ------------------------------------------------------------------------------
# Hardware device selection
# ------------------------------------------------------------------------------
set(EXAMPI_LIBFABRIC_PROVIDER
    "tcp"
    CACHE
      STRING
      "The provider cxi(Cray Slingshot)/efa(Amazon Elastic)/gni(Cray Gemini)/psm2(Intel Omni-Path)/tcp/verbs(Infiniband), shm, lnx"
)
set_property(
  CACHE EXAMPI_LIBFABRIC_PROVIDER
  PROPERTY STRINGS
           "cxi"
           "efa"
           "gni"
           "psm2"
           "tcp"
           "verbs"
           "shm"
           "lnx")

exampi_libfabric_add_config_define_namespace(
  DEFINE HAVE_LIBFABRIC_PROVIDER VALUE "\"${EXAMPI_LIBFABRIC_PROVIDER}\""
  NAMESPACE libfabric)

option(EXAMPI_LIBFABRIC_V1_API "Support older libfabric@1.15" OFF)
if(EXAMPI_LIBFABRIC_V1_API)
  exampi_libfabric_add_config_define_namespace(DEFINE EXAMPI_LIBFABRIC_V1_API
                                               NAMESPACE libfabric)
endif()

# Map provider string to uppercase and create a define
string(TOUPPER "${EXAMPI_LIBFABRIC_PROVIDER}" PROVIDER_UPPER)
exampi_libfabric_add_config_define_namespace(
  DEFINE "HAVE_LIBFABRIC_${PROVIDER_UPPER}" NAMESPACE libfabric)

# Special handling for deprecated or extra cases
if(EXAMPI_LIBFABRIC_PROVIDER STREQUAL "sockets")
  message(
    WARNING
      "The
      Sockets
      provider
      is
      deprecated
      in
      favor
      of
      the
      tcp,
      udp,
      and
      utility
      providers")
endif()

# Special handling for gni provider needing PMIx
if(EXAMPI_LIBFABRIC_PROVIDER STREQUAL "gni")
  set(_libfabric_libraries ${_libfabric_libraries} PMIx::libpmix)
endif()

# ------------------------------------------------------------------------------
# Performance counters
# ------------------------------------------------------------------------------
set(EXAMPI_LIBFABRIC_WITH_PERFORMANCE_COUNTERS
    OFF BOOL STRING "Enable libfabric performance counters (default: OFF)")
mark_as_advanced(EXAMPI_LIBFABRIC_WITH_PERFORMANCE_COUNTERS)

if(EXAMPI_LIBFABRIC_WITH_PERFORMANCE_COUNTERS)
  exampi_libfabric_add_config_define_namespace(
    DEFINE EXAMPI_LIBFABRIC_HAVE_PERFORMANCE_COUNTERS NAMESPACE libfabric)
endif()
