# ---------------------------------------------------------------------
# Function to add config defines to a list that depends on a namespace variable #defines that match
# the namespace can later be written out to a file
# ---------------------------------------------------------------------
function(libfatbat_add_config_define_namespace)
  set(options)
  set(one_value_args DEFINE NAMESPACE)
  set(multi_value_args VALUE)
  cmake_parse_arguments(OPTION "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  set(DEF_VAR FATBAT_CONFIG_DEFINITIONS_${OPTION_NAMESPACE})

  # to avoid extra trailing spaces (no value), use an if check
  if(OPTION_VALUE)
    set_property(GLOBAL APPEND PROPERTY ${DEF_VAR} "${OPTION_DEFINE} ${OPTION_VALUE}")
  else()
    set_property(GLOBAL APPEND PROPERTY ${DEF_VAR} "${OPTION_DEFINE}")
  endif()
endfunction()

# ---------------------------------------------------------------------
# Function to write out all the config defines for a given namespace into a config file
# ---------------------------------------------------------------------
function(libfatbat_write_config_defines_file)
  set(options)
  set(one_value_args TEMPLATE NAMESPACE FILENAME)
  set(multi_value_args)
  cmake_parse_arguments(OPTION "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  get_property(DEFINITIONS_VAR GLOBAL PROPERTY FATBAT_CONFIG_DEFINITIONS_${OPTION_NAMESPACE})

  if(DEFINED DEFINITIONS_VAR)
    list(SORT DEFINITIONS_VAR)
    list(REMOVE_DUPLICATES DEFINITIONS_VAR)
  endif()

  set(namespace_config_defines "\n")
  foreach(def ${DEFINITIONS_VAR})
    set(namespace_config_defines "${namespace_config_defines}#define ${def}\n")
  endforeach()

  # if the user has not specified a template, generate a proper header file
  if(NOT OPTION_TEMPLATE)
    string(TOUPPER ${OPTION_NAMESPACE} NAMESPACE_UPPER)
    set(PREAMBLE
        "\n" "// Do not edit this file! It has been generated by the cmake configuration step.\n"
        "\n" "#ifndef FATBAT_CONFIG_${NAMESPACE_UPPER}_HPP\n"
        "#define FATBAT_CONFIG_${NAMESPACE_UPPER}_HPP\n"
    )
    set(TEMP_FILENAME "${PROJECT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/${NAMESPACE_UPPER}")
    file(WRITE ${TEMP_FILENAME} ${PREAMBLE} ${namespace_config_defines} "#endif\n")
    configure_file("${TEMP_FILENAME}" "${OPTION_FILENAME}" COPYONLY)
    file(REMOVE "${TEMP_FILENAME}")
  else()
    configure_file("${OPTION_TEMPLATE}" "${OPTION_FILENAME}" @ONLY)
  endif()
endfunction()

include(CMakeParseArguments)

# ------------------------------------------------------------------------------
# Hardware device selection
# ------------------------------------------------------------------------------
set(FATBAT_PROVIDER
    "tcp"
    CACHE
      STRING
      "The provider cxi(Cray Slingshot)/efa(Amazon Elastic)/gni(Cray Gemini)/psm2(Intel Omni-Path)/tcp/verbs(Infiniband), shm, lnx"
)
set_property(
  CACHE FATBAT_PROVIDER
  PROPERTY STRINGS
           "cxi"
           "efa"
           "gni"
           "psm2"
           "tcp"
           "verbs"
           "shm"
           "lnx"
)

libfatbat_add_config_define_namespace(
  DEFINE HAVE_LIBFATBAT_PROVIDER VALUE "\"${FATBAT_PROVIDER}\"" NAMESPACE libfatbat
)

option(FATBAT_V1_API "Support older libfabric@1.15" OFF)
if(FATBAT_V1_API)
  libfatbat_add_config_define_namespace(DEFINE FATBAT_V1_API NAMESPACE libfatbat)
endif()

# Map provider string to uppercase and create a define
string(TOUPPER "${FATBAT_PROVIDER}" PROVIDER_UPPER)
libfatbat_add_config_define_namespace(DEFINE "HAVE_LIBFATBAT_${PROVIDER_UPPER}" NAMESPACE libfatbat)

# Special handling for deprecated or extra cases
if(FATBAT_PROVIDER STREQUAL "sockets")
  message(
    WARNING "The Sockets provider is deprecated in favor of the tcp, udp, and utility providers"
  )
endif()

# Special handling for gni provider needing PMIx
if(FATBAT_PROVIDER STREQUAL "gni")
  set(_libfabric_libraries ${_libfabric_libraries} PMIx::libpmix)
endif()
